[program:fastapi-app]
command=/home/projectAdmin-user/ime-ai/gunicorn_start
user=projectAdmin-user
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/projectAdmin-user/ime-ai/logs/gunicorn-error.log